### ISSUE TITLE
Implementing Changes in increasing regeneration

### ISSUE THREAD

**Issue by Kojima-Tatsuki** [Kojima-Tatsuki/BlackSmith_JRPG#15]
## Purpose
Create something that changes an unimplemented increasing regeneration.

## Task lists
+ [ ] Declare data if it has not been declared
+ [ ] Changing the increasing regeneration
+ [ ] Making changes to the current value

## Definition of Done
The character's health must be restored at regular intervals.

## Reference
#10 
#14 

## Matters to keep in mind
+ Enemies are not naturally resilient.

## Matters for consideration
+
