### ISSUE TITLE
Creating a InputTranslater

### ISSUE THREAD

**Issue by Kojima-Tatsuki** [Kojima-Tatsuki/BlackSmith_JRPG#18]
## Purpose
Creating components that can be converted from UnityEngine's input process to your own input events.
UnityEngineの入力処理から自前の入力イベントに変換させるコンポーネントを作成すること

## Task lists
+ [ ] Getting input from UnityEnging.Input
[](    UnityEnging.Inputからの入力の取得)
+ [ ] Getting the Game State
[](    ゲーム状態の取得)
+ [ ] Convert and pass it to InputEventProvider
[](    InputEventProviderに変換して渡す)

## Definition of Done
The input events must be passed to the InputEventProvider
InputEventProviderに入力イベントを渡していること

## Reference
#17 Creating components to manage the state of the game

## Matters to keep in mind
+ We need to decide if you want to create data that only records pure keystrokes.
純粋なキー入力だけを記録するデータの作成を行うかを決定する必要がある

## Matters for consideration
+
